title: Webcomic
description: "Some Webcomic"
url: https://voxelmanip.se

baseurl: /

lang: en_GB

permalink: pretty

sass:
  style: compressed
  sourcemap: never

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols:
    hellip: "..."

collections:
  comics:
    output: true
    layout: comic

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "comics"
    values:
      layout: "comic"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
